const shop = { 
    "cvv" :[{
        "BIN": 473404,
        "TYPE": "VISA",
        "LEVEL": "CLASSIC",
        "CLASS": "DEBIT",
        "ZIP": 301,
        "EXP": "Feb-24",
        "BASE": "FRESH_BASE",
        "COUNTRY": "UNITED STATES",
        "BANK": "ITS BANK",
        "PRICE": 30,
      },
      {
        "BIN": 481580,
        "TYPE": "VISA",
        "LEVEL": "CLASSIC",
        "CLASS": "DEBIT",
        "ZIP": 902,
        "EXP": "Jul-25",
        "BASE": "FRESH_BASE",
        "COUNTRY": "UNITED STATES",
        "BANK": "CENTRAL PACIFIC BANK",
        "PRICE": 30,
      },
      {
        "BIN": 442567,
        "TYPE": "VISA",
        "LEVEL": "CLASSIC",
        "CLASS": "DEBIT",
        "ZIP": 902,
        "EXP": "Jul-24",
        "BASE": "FRESH_BASE",
        "COUNTRY": "UNITED STATES",
        "BANK": "WELLS FARGO BANK, N.A.",
        "PRICE": 30,
      },
      {
        "BIN": 538505,
        "TYPE": "MASTERCARD",
        "LEVEL": "PREPAID",
        "CLASS": "DEBIT",
        "ZIP": 208,
        "EXP": "Aug-23",
        "BASE": "FRESH_BASE",
        "COUNTRY": "UNITED STATES",
        "BANK": "WEST SUBURBAN BANK",
        "PRICE": 30,
      },
      {
        "BIN": 451207,
        "TYPE": "VISA",
        "LEVEL": "PLATINUM",
        "CLASS": "DEBIT",
        "ZIP": 550,
        "EXP": "Feb-23",
        "BASE": "FRESH_BASE",
        "COUNTRY": "UNITED STATES",
        "BANK": "REGIONS BANK",
        "PRICE": 30,
      }]
   }